import { SupabaseAuthClient } from '@supabase/supabase-js/dist/module/lib/SupabaseAuthClient'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { supabase } from '../constants'

const Home: NextPage = () => {
  const some = async () => {
const {data, error} = await supabase.from('bikes')
  .select('*, bike_user!inner(reservation_start_date, reservation_end_date)')
  .gt('bike_user.reservation_start_date', '2022-01-01 15:00:00.000')
  .lt('bike_user.reservation_end_date', '2022-11-01 19:00:00.000')
if(error) {
console.log('Error:',error);
} else {
  console.log(data);
}
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={some}>press</button>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
